var sounds = [
{ "name":"Angry Creature", "file":"halloween.it/ANGRY_GR.ogg" },
{ "name":"Argh 2", "file":"halloween.it/argh.ogg" },
{ "name":"Argh 3", "file":"halloween.it/Ug1.ogg" },
{ "name":"Argh 4", "file":"halloween.it/Ug2.ogg" },
{ "name":"Argh", "file":"halloween.it/s1.ogg" },
{ "name":"Breaking Glass", "file":"ava7.com/glass-breaks.ogg" },
{ "name":"Cat 1", "file":"curly.johnson/cats.ogg" },
{ "name":"Cat 2", "file":"ava7.com/cat-scream.ogg" },
{ "name":"Cat 3", "file":"ava7.com/cat-screech.ogg" },
{ "name":"Chain Rattle", "file":"ava7.com/chains-rattle-and-ghoul.ogg" },
{ "name":"Cobra", "file":"halloween.it/COBRA_HI.ogg" },
{ "name":"Door 1", "file":"curly.johnson/door.ogg" },
{ "name":"Door 2", "file":"ava7.com/creak-door.ogg" },
{ "name":"Door 3", "file":"ava7.com/creak-door-2.ogg" },
{ "name":"Door 4", "file":"halloween.it/DOORCREK.ogg" },
{ "name":"Echoing Walk", "file":"ava7.com/echo-walk.ogg" },
{ "name":"Fall", "file":"halloween.it/FALLING.ogg" },
{ "name":"Falling down stairs", "file":"halloween.it/MAN_FALL.ogg" },
{ "name":"Ferocious Beast", "file":"halloween.it/BROWN_BE.ogg" },
{ "name":"Footsteps", "file":"curly.johnson/footsteps.ogg" },
{ "name":"Fright", "file":"halloween.it/FRIGHT.ogg" },
{ "name":"Ghost 1", "file":"partnersinrhyme.com/Azghost.ogg" },
{ "name":"Ghost 2", "file":"partnersinrhyme.com/ghost01.ogg" },
{ "name":"Ghost 3", "file":"partnersinrhyme.com/GHOST8B.ogg" },
{ "name":"Ghostly 1", "file":"curly.johnson/ghostly1.ogg" },
{ "name":"Ghostly 2", "file":"curly.johnson/ghostly2.ogg" },
{ "name":"Graveyard", "file":"curly.johnson/graveyard.ogg" },
{ "name":"Happy Halloween", "file":"curly.johnson/happyhw.ogg" },
{ "name":"Haunted House", "file":"partnersinrhyme.com/hauntedhouse.ogg" },
{ "name":"Heartbeat 1", "file":"curly.johnson/heartbeat.ogg" },
{ "name":"Heartbeat 2", "file":"halloween.it/NORMAL_H.ogg" },
{ "name":"Heartbeat 3", "file":"halloween.it/Heartbeat.ogg" },
{ "name":"Heartbeat 4", "file":"halloween.it/RAPID_HE.ogg" },
{ "name":"Laugh 1", "file":"curly.johnson/laugh.ogg" },
{ "name":"Laugh 2", "file":"curly.johnson/laugh2.ogg" },
{ "name":"Laugh 3", "file":"ava7.com/evil-laugh.ogg" },
{ "name":"Laugh 4", "file":"halloween.it/BIG_LAFF.ogg" },
{ "name":"Laugh 5", "file":"halloween.it/CRAZY_LF.ogg" },
{ "name":"Laugh 6", "file":"halloween.it/l1.ogg" },
{ "name":"Laugh 7", "file":"halloween.it/l2.ogg" },
{ "name":"Laugh 8", "file":"halloween.it/l3.ogg" },
{ "name":"Laugh 9", "file":"halloween.it/LOTS_LFF.ogg" },
{ "name":"Laugh 10", "file":"halloween.it/NUTHOUSE.ogg" },
{ "name":"Laugh 11", "file":"halloween.it/CNDI_LF1.ogg" },
{ "name":"Laugh 12", "file":"halloween.it/l5.ogg" },
{ "name":"Laugh 13", "file":"curly.johnson/witch.ogg" },
{ "name":"Laugh 14", "file":"partnersinrhyme.com/wickedwitchlaugh.ogg" },
{ "name":"Monster Footsteps", "file":"halloween.it/BIG_FOOT.ogg" },
{ "name":"Monster", "file":"ava7.com/scary-monster.ogg" },
{ "name":"Ooow", "file":"curly.johnson/ooow.ogg" },
{ "name":"Organ Music", "file":"curly.johnson/organmusic.ogg" },
{ "name":"Owl 1", "file":"curly.johnson/owl.ogg" },
{ "name":"Owl 2", "file":"ava7.com/owl.ogg" },
{ "name":"Rain", "file":"halloween.it/RAIN_WD.ogg" },
{ "name":"Scream 1", "file":"curly.johnson/scream.ogg" },
{ "name":"Scream 2", "file":"curly.johnson/scream2.ogg" },
{ "name":"Scream 3", "file":"ava7.com/blood-scream.ogg" },
{ "name":"Scream 3", "file":"ava7.com/women-scream.ogg" },
{ "name":"Scream 4", "file":"halloween.it/Ahhh.ogg" },
{ "name":"Scream 5", "file":"partnersinrhyme.com/AAAGH1.ogg" },
{ "name":"Scream 6", "file":"partnersinrhyme.com/falling.ogg" },
{ "name":"Scream 7", "file":"partnersinrhyme.com/suicide.ogg" },
{ "name":"Spooky 1", "file":"curly.johnson/spooky.ogg" },
{ "name":"Spooky 2", "file":"curly.johnson/spooky2.ogg" },
{ "name":"Storm", "file":"curly.johnson/storm.ogg" },
{ "name":"Suspense 1", "file":"ava7.com/suspense-2.ogg" },
{ "name":"Suspense 2", "file":"halloween.it/BIG_ENTR.ogg" },
{ "name":"Thunder", "file":"halloween.it/BIG_THUN.ogg" },
{ "name":"Twilight Zone", "file":"ava7.com/twilight-zone.ogg" },
{ "name":"Welcome", "file":"curly.johnson/welcome.ogg" },
{ "name":"Wind 1", "file":"curly.johnson/wind.ogg" },
{ "name":"Wind 2", "file":"ava7.com/windy.ogg" },
{ "name":"Wind 3", "file":"halloween.it/HOWLINGW.ogg" },
{ "name":"Wind 4", "file":"halloween.it/HOWLNGW2.ogg" },
{ "name":"Witch's Cauldron 1", "file":"curly.johnson/wtchbrew.ogg" },
{ "name":"Witch's Cauldron 2", "file":"halloween.it/WITCHES.ogg" },
{ "name":"Wolf 1", "file":"curly.johnson/wolf.ogg" },
{ "name":"Wolf 2", "file":"ava7.com/werewolf-howl.ogg" },
{ "name":"Wolf 3", "file":"halloween.it/WOLF_HOW.ogg" },
{ "name":"Wolf 4", "file":"partnersinrhyme.com/Wolf Howl.ogg" },
{ "name":"Zombie 1", "file":"halloween.it/Zombie1.ogg" },
{ "name":"Zombie 2", "file":"halloween.it/Zombie2.ogg" },
{ "name":"Zombie 3", "file":"minecraft/zombie1.ogg" },
{ "name":"Zombie 4", "file":"minecraft/zombie2.ogg" },
{ "name":"Zombie 5", "file":"minecraft/zombie3.ogg" },
{ "name":"Zombie 6", "file":"minecraft/zombiedeath.ogg" },
{ "name":"Zombie 7", "file":"minecraft/zombiehurt1.ogg" },
{ "name":"Zombie 8", "file":"minecraft/zombiehurt2.ogg" }
];
